version: '3'

services:
  db:
    image: mysql:8.0 # Image MySQL 8.0
    restart: always
    ports:
      - "3906:3306" # Map the port of MySQL to the host
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Root password
      MYSQL_DATABASE: ${DB_NAME}         # DB Name
    container_name: cogsz
    volumes:
      - ./mysql_data:/var/lib/mysql # Mount the volume 