name: Run Tests

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Specify Node.js v16 here

      - name: Install Dependencies
        run: yarn install # Or npm install if you use npm

      - name: Run Tests
        run: yarn test # Replace with your test command

      - name: Check Test Status
        id: test-status
        run: |
          if [ -f ./test-results.xml ]; then
            echo 'status=failed' >> $GITHUB_ENV
          else
            echo 'status=passed' >> $GITHUB_ENV
          fi

      - name: Commit on Test Pass
        if: env.test-status == 'passed'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Tests passed on ${{ github.sha }}"
          git push

      - name: Send Custom Message on Test Failure
        if: env.test-status == 'failed'
        run: |
          echo "Tests failed on ${{ github.sha }}"  # Add your custom message here
